name: CI

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Conccrete Node.js version to use'
        type: string
      matrix-node-version:
        description: 'Node.js versions to use, json array like in matrix.node-version'
        type: string
      matrix-node-version-earliest:
        description: 'If earliest Node.js version should be used from matrix-node-version'
        type: boolean
        default: false
      install-script:
        description: 'Install script to run'
        type: string
        default: npm ci
      run-script:
        description: 'Check script to run'
        type: string
        default: |
          npm run check
          npm run lint

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  # echo-inputs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: ${{ tojson(inputs) }}
  #       shell: cat {0}
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: kt-actions/npm-run-script@v1
        with:
          node-version: ${{ inputs.node-version }}
          matrix-node-version: ${{ inputs.matrix-node-version }}
          matrix-node-version-earliest: ${{ inputs.matrix-node-version-earliest }}
          install-script: ${{ inputs.install-script }}
          run-script: ${{ inputs.run-script }}
