name: CI-sonar

on:
  workflow_call:
    inputs:
      matrix-node-version:
        description: 'Node.js versions to use, json array like in matrix.node-version'
        type: string
      install-script:
        description: 'Install script to run'
        type: string
        default: npm ci
      run-script:
        description: 'Script to run before the sonar action'
        type: string
        default: |
          npm run build
          npm run coverage
    secrets:
      sonar-token:
        description: 'SonarQube token'
        required: false

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  # echo-inputs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: ${{ tojson(inputs) }}
  #       shell: cat {0}
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: kt-actions/npm-run-script@v1
        with:
          matrix-node-version: ${{ inputs.matrix-node-version }}
          install-script: ${{ inputs.install-script }}
          run-script: ${{ inputs.run-script }}

      - uses: sonarsource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.sonar-token }}
