name: CI-test

on:
  workflow_call:
    inputs:
      matrix-node-version:
        description: 'Node.js versions to use, json array like in matrix.node-version'
        type: string
      install-script:
        description: 'Install script to run'
        type: string
        default: npm ci
      run-script:
        description: 'Check script to run'
        type: string
        default: |
          npm run build
          npm run test

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  # echo-inputs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: ${{ tojson(inputs) }}
  #       shell: cat {0}
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(inputs.matrix-node-version) }}
    steps:
      - uses: actions/checkout@v4

      - uses: kt-actions/npm-run-script@v1
        with:
          node-version: ${{ matrix.node-version }}
          install-script: ${{ inputs.install-script }}
          run-script: ${{ inputs.run-script }}
