name: CI

on:
  workflow_call:
    inputs:
      # node versions to use, json array like in matrix.node-version
      node-version:
        description: 'Conccrete Node.js version to use'
        type: string
      matrix-node-version:
        description: 'Node.js versions to use, json array like in matrix.node-version'
        type: string
      check-script:
        description: 'Check script to run'
        type: string
        default: |
          npm run check
          npm run lint
      test-script:
        description: 'Test script to run'
        type: string
        default: |
          npm run build
          npm test
      run-sonar:
        description: 'Run SonarQube analysis'
        type: boolean
        default: false
      sonar-script:
        description: 'SonarQube script to run'
        type: string
        default: |
          npm run build
          npm run coverage
    secrets:
      sonar-token:
        description: 'SonarQube token'
        required: false

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  check:
    uses: ./.github/workflows/ci-check.yml@v1
    with:
      node-version: ${{ inputs.node-version }}
      matrix-node-version: ${{ vars.MATRIX_NODE_VERSION }}
